# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9382ae805c5546f1a0cfcaa334a438f21abfc4d658dc0b8d9cdf2210a7320d8880b21f70d8305db5aeec6e29c0be0a29800c5d682236443d50342abd441cf639

test:
  secret_key_base: f86387f0a7984fade71cf4cf1ae5032bccd55e0782731bcece05f682470a6d640f91313703e3e420610c179f6f22e4410ff1bcda7cd47f9645b114d33eb7a54a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
